apiVersion: v1
kind: Secret
metadata:
  name: opensign-secrets
  namespace: opensign
type: Opaque
stringData:
  # Required
  MASTER_KEY: "CHANGE-ME-12-char-min"
  MONGODB_URI: "mongodb://opensign-mongo:27017/OpenSignDB"
  PFX_BASE64: ""
  PASS_PHRASE: ""

  # SMTP (only if SMTP_ENABLE=true)
  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_USERNAME: ""
  SMTP_USER_EMAIL: ""
  SMTP_PASS: ""
